### ISSUE TITLE
How to configure endpoints?

### ISSUE THREAD

**Issue by mdlincoln** [dvcama/LodLive#17]
I've tried to input this resource URI: `http://collection.britishmuseum.org/id/object/PPA82633`, however this returns the error message "no endpoint configured for the resource". I recall being able to visualize resources from the British Museum LOD in the past on lodlive - has the software changed?

**Comment by dvcama** [comment]
Hi,
lodlive is pure javascript so I use a "Sesame proxy" to extract data from any resources from "unknown" domain (with no sparql configured)

well, the proxy was offline 

I have configured the proper endpoint (it works better now) but sadly britishmuseum uses a pure CIDOC approach so I cannot show the titles of the resources without changing the lodlive standard SPARQL queries. If you want it working better for this domain you have to download lodlive and configure it by yourself

bye

**Comment by JPEvain** [comment]
Hello,
I have downloaded lodlive and I am working on its configuration. 
I am starting with something basic:
1. declare my localhost endpoint for my triple store
2. provide an example 

I start from live on lodlive but maybe this is not applying to local stores?

Otherwise it says the endpoint is not configured for the query. I got the query from the "information" text attached to the node. I tested it on workbench and the query is rights and well formed returning the appropriate results. 

I don't know what to try next.. Any hint?

I wish I could make it work (I am working on a PoC for sport) as lodlive is very appealing.

Jean-Pierre

**Comment by JPEvain** [comment]
I have made some progress but getting stuck again further down the line...

1. I have customised the orange box and can do the autocomplete and resource discovery 
2. I have also modified the "default" profile and I can see in the console that the query is made and results returned as xml.

Still hovering over the default node returns a message saying "no endpoint has been configured"...

Is my profile definition incomplete?

thanks in advance for any hint.

jean-Pierre

**Comment by JPEvain** [comment]
I still have "no endpoint configured for that resource" but thing have been moving forward.

2 comments:
- the example profile should include the declaration of the endpointType so that data is correctly returned in Json 
- the endpointType is not taken into account in lodlive.core.js and in my case all queries were wrongly returning xml from my sesame server

**Comment by leticiaverona** [comment]
Hello @JPEvain, Did you succeed? I am also trying to use LodLive locally and got the "no endpoint'.
