### ISSUE TITLE
Browsing LOD published as JSON-LD doesn't work

### ISSUE THREAD

**Issue by jaw111** [dvcama/LodLive#24]
For example:
http://en.lodlive.it/?http://musicbrainz.org/release-group/d3bc1a64-7561-3787-b680-0003aa50f8f1

Is it possible to add support for JSON-LD?

**Comment by dvcama** [comment]
LodLive support JSON-LD via a simple Jena Proxy, does musicbrainz.org support content negotiation?

**Comment by jaw111** [comment]
Yes MusicBrainz does support conneg if you try with "Accept: application/ld+json" but I am not sure the support is perfect (like if you use q factor).

What Accept header is the proxy sending in the request?

Regards,
John

**Comment by CaptSolo** [comment]
Has this problem been resolved? I am trying to browse JSON-LD resources with LodLive but it does not work.

Example: https://json-ld.org/test-suite/tests/compact-0025-in.jsonld

**Comment by dvcama** [comment]
@CaptSolo lodlive will never work with that example because the URL that you are opening:
`https://json-ld.org/test-suite/tests/compact-0025-in.jsonld`
is not the URI of the resource `http://example.com/queen`

@jaw111 sorry but the old sesame proxy don't understand your resource 
http://en.lodlive.it/?http://musicbrainz.org/release-group/d3bc1a64-7561-3787-b680-0003aa50f8f1
Jena instead does it 
[https://lodview.it/lodview/?IRI=https%3A%2F%2Fmusicbrainz.org%2Frelease-group%2Fd3bc1a64-7561-3787-b680-0003aa50f8f1&sparql=<>&prefix=https%3A%2F%2Fmusicbrainz.org%2Frelease-group%2Fd3bc1a64-7561-3787-b680-0003aa50f8f1](https://lodview.it/lodview/?IRI=https%3A%2F%2Fmusicbrainz.org%2Frelease-group%2Fd3bc1a64-7561-3787-b680-0003aa50f8f1&sparql=<>&prefix=https%3A%2F%2Fmusicbrainz.org%2Frelease-group%2Fd3bc1a64-7561-3787-b680-0003aa50f8f1)

I hope to find time someday to update the proxy
